---
- name: make haproxystats-pull systemd file
  template:
    src: haproxystats-pull.service.j2
    dest: /etc/systemd/system/haproxystats-pull.service
    backup: yes

- name: make haproxystats-process systemd file
  template:
    src: haproxystats-process.service.j2
    dest: /etc/systemd/system/haproxystats-process.service
    backup: yes
